### ISSUE TITLE
Documenting and Improving Axis Conventions

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/AprilTags.jl#64]
Hi @Affie, could you please confirm the following regarding the C-library and ccall part only please:

https://github.com/JuliaRobotics/AprilTags.jl/blob/8f2a739cd7b4b7a43f2f81342ceeebc026f396e8/src/wrapper.jl#L434-L448

- Image axes start top left corner, assume 640x480 resolution
- `fx == width`, that is normal image from left to right, i.e. the 640 dimension;
- `fy == height`, that is down vertically, i.e. the 480 dimension;
- similar for `cx` and `cy`

It's really hard to pin this down because it is not documented here.  I'm trying to document that here and then also improve the API at the higher level code.  Will keep the low level wrapper code the same as is happening in the C library.

**Comment by Affie** [comment]
Looks good

**Comment by dehann** [comment]
see #62 and #63
