### ISSUE TITLE
Double check axes in test/documentation

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/AprilTags.jl#66]
hi @Affie , could you perhaps please help check these numbers / conventions:  I understand `cx <==> c_width` and `cy <==> c_height`, but if a general case has `c_height < c_width` (e.g. image is 16:9 <==> w:h) then this is a little confusing:

https://github.com/JuliaRobotics/AprilTags.jl/blob/9ab7cadba8cbe64fc6deaf31a13d8b040ba331e2/test/basictests.jl#L125-L131

since current text suggests `cx < cy` (i.e. `c_width < c_height`), but that is opposite axis convention?  If so, then this might be the source of the convention trouble I've been struggling through.
 
For camera reference we have `x` pointing right and `y` pointing down.  For Images.jl `::Array` (i.e. image frame here in Julia) we have `img[i,j]` where `(j,i) <==> (x,y) <==> (w,h)`.  Top left corner of image is `(0,0)`.

The example listed in the docs was copied (with same potential bug) from the tests:
https://juliarobotics.org/AprilTags.jl/latest/#Example-from-Tests-1

**Comment by Affie** [comment]
Also have a look at the apriltag library documentation here: https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#coordinate-system

**Comment by Affie** [comment]
It does look like the x,y from the test are correct, but that does not correlate with the coordinate system the c library claims. I'm still looking into it.

**Comment by Affie** [comment]
The tests in homography are correct, the other tests needs a -fx for drawing the tags.

**Comment by dehann** [comment]
Hi @Affie, but what about the issue of `cx < cy` -- there is no way that is right according to how I understand it?  The regular images we work with CANNOT HAVE `width < height`???

No argument whether `+fx` or `-fx` is right or not, and probably is an issue, however, that doesn't stop a potential second bug.  So lets leave `-fx` out of this thread if possible (likely two bugs sorta canceling out or some weirdness). 

We need to be 100% sure that `x == width` and `y == height`?  If so then IT MUST BE TRUE THAT `cy < cx` which MUST MEAN THE UNIT TEST IS WRONG:
https://github.com/JuliaRobotics/AprilTags.jl/blob/9ab7cadba8cbe64fc6deaf31a13d8b040ba331e2/test/basictests.jl#L128-L129

The test currently says `cx < cy` -- that cannot be???  Or I'm totally missing whats going on here...

**Comment by dehann** [comment]
PS, i wrote a whole camera calibration stack with `cy < cx` -- and looked like what I have is working?
https://github.com/JuliaRobotics/AprilTags.jl/blob/9ab7cadba8cbe64fc6deaf31a13d8b040ba331e2/test/testAprilGridCalibration.jl#L52-L53

**Comment by Affie** [comment]
Sorry, should have been more clear, these tests are the correct ones: https://github.com/JuliaRobotics/AprilTags.jl/blob/master/test/homography.jl

With the others, it doesn't really matter what cx and cy is. But it can be confusing, so I updated it (locally, will still pr).

**Comment by Affie** [comment]
Here is an easy verification to test the correct one:

```julia
using AprilTags
using Images

detector = AprilTagDetector()

projImg = zeros(Gray{N0f8}, 480,640)
tag0 = kron(getAprilTagImage(0), ones(Gray{N0f8}, 4,4))
projImg[221:260,301:340] = tag0
projImg

fx = 1000.
fy = 1000.
cx = 320.
cy = 240.

K = [fx 0  cx;
      0 fy cy]

tags = detector(projImg)

imCol = RGB.(projImg)
foreach(tag->drawTagBox!(imCol, tag), tags)

taglength = 0.1
(tags, poses) = detectAndPose(detector, projImg, fx, fy, cx, cy, taglength)

poses[1]
```
results
```
3×4 Array{Float64,2}:
  0.996868    0.00273632   0.079042   -0.000300523
  0.00256118  0.99776     -0.0668423  -0.000417185
 -0.0790478   0.0668353    0.994628    3.1166
```

**Comment by dehann** [comment]
ah okay, that makes more sense thanks.  This is a cool example, perhaps add that to the documentation -- I'll copy it over and send a PR
